[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Lab2"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.2.3,<3"
numpy = ">=2.2.1,<3"
scikit-learn = ">=1.6.1,<2"
pip = ">=25.0,<26"
ipykernel = ">=6.29.5,<7"
matplotlib = ">=3.10.0,<4"
seaborn = ">=0.13.2,<0.14"
